[package]
name = "unabbreviated-rust-example"
version = "0.1.0"
edition = "2024"

[dependencies]
unabbreviated-rust = { path = "../unabbreviated-rust" }

# [build-dependencies]
# unabbreviated-rust = { path = "../unabbreviated-rust" }
