[package]
name = "unabbreviated-example"
version = "0.1.0"
edition = "2024"

[dependencies]
unabbreviated = { path = "../unabbreviated" }

# [build-dependencies]
# unabbreviated = { path = "../unabbreviated" }
